# Настройка надписи над могилой
# Поддерживаемые плейсхолдеры:
# %player% - ник умершего игрока
# %time% - оставшееся время в формате ММ:СС
grave-holo-text: "&7Могила &e%player% &7[&c%time%&7]"
quick-up-enabled: true
